### ISSUE TITLE
Add inVent variables

### ISSUE THREAD

**Issue by MysterDead** [Impostors-ga/Impostor-Server#3]
# Api Suggestion

## Suggestion
Add to [**Impostor.Api.Net.Inner.Objects.IInnerPlayerControl**](https://github.com/Impostor/Impostor/blob/dev/src/Impostor.Api/Net/Inner/Objects/IInnerPlayerInfo.cs) boolean `InVent`

## Use case
```
player.Character.PlayerInfo.inVent() // true/false
```

**Comment by mrchomik892** [comment]
It looks good, i will test it today
